name: Build
on:
  push:
    branches:
      - "amogus"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/0d9e-tech/web:latest
